name: Build and Deploy to Hostinger

on:
  push:
    branches:
      - main  # change if you use a different branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Install FTP client
        run: sudo apt-get install -y lftp

      - name: Deploy via FTP to Hostinger
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          lftp -e "mirror -R .evershop/build /public_html; quit" -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER
